version: "3"
services:
  database:
    container_name: "postgres"
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FoodExpenses
    ports:
      - "5432:5432"
    networks:
      - custom
  database_test:
    container_name: "postgres_test"
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgrestest
      - POSTGRES_PASSWORD=postgrestest
      - POSTGRES_DB=FoodExpensesTest
    ports:
      - "5433:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge