"""DB creation

Revision ID: 17caba9a8c79
Revises: 
Create Date: 2023-09-14 15:02:30.396876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17caba9a8c79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('shipment_num', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=False),
    sa.Column('shipment_status', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=True),
    sa.Column('shipment_date', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=True),
    sa.Column('shipping_address', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('bonuses', sa.Integer(), nullable=True),
    sa.Column('assembly_and_delivery', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_num')
    )
    op.create_table('products',
    sa.Column('product_name', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=True),
    sa.Column('quantity', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_status', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=True),
    sa.Column('shipment_num', sa.String().with_variant(sa.VARCHAR(), 'postgresql'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_num'], ['shipments.shipment_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('shipments')
    # ### end Alembic commands ###
